name: objective_db
description: BSON based Database
version: 0.3.1+25
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  power_plant: ^1.0.2+3
  chromarotor: ^1.0.5
  bson: ^5.0.8

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
